trigger:
  branches:
    include:
    - main
  paths:
    include:
    - bannedPasswords/parameters

pool:
  vmImage: ubuntu-latest

variables:
  - name: ParameterFolderPath
    value: bannedPasswords/parameters

stages:
  - stage: TenantA
    jobs:
    - job: TenantA
      displayName: Updating Password Settings in Tenant A
      steps:
        - task: AzurePowerShell@5
          displayName: Setting the configuration
          inputs:
            azureSubscription: "TenantA-AuthenticationMethods-SPN"
            ScriptType: "FilePath"
            ScriptPath: "$(System.DefaultWorkingDirectory)/bannedPasswords/code/Set-PasswordSettings.ps1"
            ScriptArguments:
              -ParameterFolderPath "$(System.DefaultWorkingDirectory)/$(ParameterFolderPath)"
              -TenantBannedPasswordsFilePath "$(System.DefaultWorkingDirectory)/$(ParameterFolderPath)/bannedPasswords-TenantA.json"
            azurePowerShellVersion: LatestVersion

  - stage: TenantB
    jobs:
    - job: TenantB
      displayName: Updating Password Settings in Tenant B
      steps:
        - task: AzurePowerShell@5
          displayName: Setting the configuration
          inputs:
            azureSubscription: "TenantB-AuthenticationMethods-SPN"
            ScriptType: "FilePath"
            ScriptPath: "$(System.DefaultWorkingDirectory)/bannedPasswords/code/Set-PasswordSettings.ps1"
            ScriptArguments:
              -ParameterFolderPath "$(System.DefaultWorkingDirectory)/$(ParameterFolderPath)"
              -TenantBannedPasswordsFilePath "$(System.DefaultWorkingDirectory)/$(ParameterFolderPath)/bannedPasswords-TenantB.json"
            azurePowerShellVersion: LatestVersion